# Generated by Django 2.2.28 on 2025-03-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniSphereApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='societyprofile',
            name='saved_students',
            field=models.ManyToManyField(blank=True, related_name='saved_by_societys', to='UniSphereApp.StudentProfile'),
        ),
        migrations.AlterField(
            model_name='societyprofile',
            name='company_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='societyprofile',
            name='company_website',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='societyprofile',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
