# Generated by Django 2.2.28 on 2025-03-27 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UniSphereApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SharedPost',
            new_name='Repost',
        ),
    ]
