# Generated by Django 2.2.28 on 2025-03-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniSphereApp', '0002_auto_20250307_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpost',
            name='caption',
            field=models.TextField(default='Enter a caption for your post'),
            preserve_default=False,
        ),
    ]
