# Generated by Django 2.2.28 on 2025-03-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniSphereApp', '0003_auto_20250327_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='societyprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='society_logos/'),
        ),
    ]
