# Generated by Django 2.2.28 on 2025-03-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniSphereApp', '0003_auto_20250323_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societyprofile',
            name='saved_students',
            field=models.ManyToManyField(blank=True, related_name='saved_by_society', to='UniSphereApp.StudentProfile'),
        ),
    ]
