# Generated by Django 2.2.28 on 2025-03-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniSphereApp', '0003_auto_20250314_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='language',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='school',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='languages',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
