# Generated by Django 2.2.28 on 2025-03-14 23:53

import UniSphereApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniSphereApp', '0004_auto_20250314_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='languages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=UniSphereApp.models.profile_picture_upload_path),
        ),
    ]
