# Generated by Django 2.2.28 on 2025-03-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UniSphereApp', '0003_sharedpost'),
        ('UniSphereApp', '0006_auto_20250320_1239'),
    ]

    operations = [
    ]
