# Generated by Django 2.2.28 on 2025-03-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniSphereApp', '0006_auto_20250318_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterprofile',
            name='company_description',
            field=models.TextField(default='Not provided'),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='company_website',
            field=models.URLField(default='Not provided'),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='location',
            field=models.CharField(default='Not provided', max_length=255),
        ),
    ]
