# Generated by Django 2.2.28 on 2025-03-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniSphereApp', '0008_auto_20250320_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='bio',
            field=models.TextField(blank=True, default='Not Set'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(blank=True, default='Not Set', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='Not Set', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='interests',
            field=models.TextField(blank=True, default='Not Set'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='languages',
            field=models.CharField(blank=True, default='Not set', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='school',
            field=models.CharField(blank=True, default='Not Set', max_length=255),
            preserve_default=False,
        ),
    ]
