# Generated by Django 2.2.28 on 2025-03-22 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UniSphereApp', '0010_auto_20250320_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpost',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UniSphereApp.Project'),
        ),
    ]
