# Generated by Django 2.2.28 on 2025-03-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniSphereApp', '0010_auto_20250320_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_studentprofile_friends_+', to='UniSphereApp.StudentProfile'),
        ),
    ]
